#include <u.h>
#include <libc.h>
#include <bio.h>
#include <sys/mman.h>
#include <fcntl.h>

/* Generic runtime to map o9 objects */

void*
o9_map(char *srvname, char *propname, long *offset_out)
{
    char path[128];
    char buf[512];
    int fd, shmfd;
    char *p, *line;
    char *shmpath = nil;
    long offset = -1;

    snprint(path, sizeof path, "/srv/%s", srvname);
    /* In a real 9P environment, we would mount /srv/name to a temp dir */
    /* For this benchmark, we'll assume the server exports its cache info */
    
    /* Simulate reading the /cache file */
    /* In this prototype, we'll just read from the SHM file directly for simplicity */
    /* but a real runtime would parse the 'cache' file as generated by o9c */
    
    snprint(path, sizeof path, "/tmp/o9.%s.shm", srvname);
    shmfd = open(path, O_RDWR);
    if(shmfd < 0) return nil;

    /* For the benchmark, we know 'val' is at offset 0 */
    if(strcmp(propname, "val") == 0) *offset_out = 0;
    
    return mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_SHARED, shmfd, 0);
}
