/* generated by tools/o9prop.py kind=width seed=170755073 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong s0 = -65536;
	vlong s1 = -32768;
	vlong s2 = 1;
	vlong s3 = 0;
	vlong s4 = 128;
	vlong s5 = -65536;
	vlong s6 = 0;
	vlong s7 = 32768;
	vlong s8 = 7;
	vlong s9 = 64;
	vlong s10 = -129;
	vlong s11 = -128;
	vlong s12 = 2;
	vlong s13 = 1023;
	vlong s14 = 32768;
	vlong s15 = 64;
	vlong s16 = 128;
	vlong s17 = 64;
	vlong s18 = -256;
	vlong s19 = 15;
	vlong s20 = -129;
	vlong s21 = 1;
	USED(s0); USED(s1); USED(s2); USED(s3); USED(s4); USED(s5); USED(s6); USED(s7); USED(s8); USED(s9); USED(s10); USED(s11); USED(s12); USED(s13); USED(s14); USED(s15); USED(s16); USED(s17); USED(s18); USED(s19); USED(s20); USED(s21);
	fprint(1, "vars %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n", s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21);
	fprint(1, "0 int8 %lld\n", (vlong)(((char)(s0))));
	fprint(1, "1 ushort %lld\n", (vlong)(((ushort)(s1))));
	fprint(1, "2 uint8 %lld\n", (vlong)(((uchar)(s2))));
	fprint(1, "3 uint64 %lld\n", (vlong)(((uvlong)(s3))));
	fprint(1, "4 char %lld\n", (vlong)(((char)(s4))));
	fprint(1, "5 int %lld\n", (vlong)(((int)(s5))));
	fprint(1, "6 uvlong %lld\n", (vlong)(((uvlong)(s6))));
	fprint(1, "7 vlong %lld\n", (vlong)(((vlong)(s7))));
	fprint(1, "8 int16 %lld\n", (vlong)(((short)(s8))));
	fprint(1, "9 byte %lld\n", (vlong)(((uchar)(s9))));
	fprint(1, "10 intptr %lld\n", (vlong)(((intptr)(s10))));
	fprint(1, "11 uint16 %lld\n", (vlong)(((ushort)(s11))));
	fprint(1, "12 uchar %lld\n", (vlong)(((uchar)(s12))));
	fprint(1, "13 int64 %lld\n", (vlong)(((vlong)(s13))));
	fprint(1, "14 uint %lld\n", (vlong)(((uint)(s14))));
	fprint(1, "15 uint32 %lld\n", (vlong)(((ulong)(s15))));
	fprint(1, "16 long %lld\n", (vlong)(((long)(s16))));
	fprint(1, "17 ulong %lld\n", (vlong)(((ulong)(s17))));
	fprint(1, "18 short %lld\n", (vlong)(((short)(s18))));
	fprint(1, "19 int32 %lld\n", (vlong)(((long)(s19))));
	fprint(1, "20 bool %lld\n", (vlong)(((s20) != 0)));
	fprint(1, "21 uintptr %lld\n", (vlong)(((uintptr)(s21))));
	exits(nil);
}
