/* generated by tools/o9prop.py kind=width seed=668680284 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong s0 = -256;
	vlong s1 = 127;
	vlong s2 = 31;
	vlong s3 = -32769;
	vlong s4 = -65536;
	vlong s5 = 127;
	vlong s6 = 65536;
	vlong s7 = 256;
	vlong s8 = 128;
	vlong s9 = -257;
	vlong s10 = 31;
	vlong s11 = 15;
	vlong s12 = 128;
	vlong s13 = -1;
	vlong s14 = 2;
	vlong s15 = 127;
	vlong s16 = 1;
	vlong s17 = 65535;
	vlong s18 = 63;
	vlong s19 = 128;
	vlong s20 = -256;
	vlong s21 = 7;
	USED(s0); USED(s1); USED(s2); USED(s3); USED(s4); USED(s5); USED(s6); USED(s7); USED(s8); USED(s9); USED(s10); USED(s11); USED(s12); USED(s13); USED(s14); USED(s15); USED(s16); USED(s17); USED(s18); USED(s19); USED(s20); USED(s21);
	fprint(1, "vars %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n", s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21);
	fprint(1, "0 char %lld\n", (vlong)(((char)(s0))));
	fprint(1, "1 long %lld\n", (vlong)(((long)(s1))));
	fprint(1, "2 int %lld\n", (vlong)(((int)(s2))));
	fprint(1, "3 uint8 %lld\n", (vlong)(((uchar)(s3))));
	fprint(1, "4 int64 %lld\n", (vlong)(((vlong)(s4))));
	fprint(1, "5 int32 %lld\n", (vlong)(((long)(s5))));
	fprint(1, "6 int8 %lld\n", (vlong)(((char)(s6))));
	fprint(1, "7 uchar %lld\n", (vlong)(((uchar)(s7))));
	fprint(1, "8 uint %lld\n", (vlong)(((uint)(s8))));
	fprint(1, "9 intptr %lld\n", (vlong)(((intptr)(s9))));
	fprint(1, "10 uintptr %lld\n", (vlong)(((uintptr)(s10))));
	fprint(1, "11 uint32 %lld\n", (vlong)(((ulong)(s11))));
	fprint(1, "12 bool %lld\n", (vlong)(((s12) != 0)));
	fprint(1, "13 uint16 %lld\n", (vlong)(((ushort)(s13))));
	fprint(1, "14 ushort %lld\n", (vlong)(((ushort)(s14))));
	fprint(1, "15 ulong %lld\n", (vlong)(((ulong)(s15))));
	fprint(1, "16 uvlong %lld\n", (vlong)(((uvlong)(s16))));
	fprint(1, "17 int16 %lld\n", (vlong)(((short)(s17))));
	fprint(1, "18 uint64 %lld\n", (vlong)(((uvlong)(s18))));
	fprint(1, "19 short %lld\n", (vlong)(((short)(s19))));
	fprint(1, "20 vlong %lld\n", (vlong)(((vlong)(s20))));
	fprint(1, "21 byte %lld\n", (vlong)(((uchar)(s21))));
	exits(nil);
}
