/* generated by tools/o9prop.py kind=width seed=1981885010 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong s0 = 7;
	vlong s1 = -257;
	vlong s2 = -65536;
	vlong s3 = -128;
	vlong s4 = 65535;
	vlong s5 = 65535;
	vlong s6 = 2;
	vlong s7 = 31;
	vlong s8 = 1;
	vlong s9 = -65537;
	vlong s10 = 15;
	vlong s11 = -128;
	vlong s12 = 1;
	vlong s13 = 255;
	vlong s14 = 65536;
	vlong s15 = -129;
	vlong s16 = 65535;
	vlong s17 = 32768;
	vlong s18 = -1;
	vlong s19 = -32769;
	vlong s20 = -257;
	vlong s21 = 64;
	USED(s0); USED(s1); USED(s2); USED(s3); USED(s4); USED(s5); USED(s6); USED(s7); USED(s8); USED(s9); USED(s10); USED(s11); USED(s12); USED(s13); USED(s14); USED(s15); USED(s16); USED(s17); USED(s18); USED(s19); USED(s20); USED(s21);
	fprint(1, "vars %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n", s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21);
	fprint(1, "0 uintptr %lld\n", (vlong)(((uintptr)(s0))));
	fprint(1, "1 long %lld\n", (vlong)(((long)(s1))));
	fprint(1, "2 int %lld\n", (vlong)(((int)(s2))));
	fprint(1, "3 uint16 %lld\n", (vlong)(((ushort)(s3))));
	fprint(1, "4 ushort %lld\n", (vlong)(((ushort)(s4))));
	fprint(1, "5 uint64 %lld\n", (vlong)(((uvlong)(s5))));
	fprint(1, "6 byte %lld\n", (vlong)(((uchar)(s6))));
	fprint(1, "7 vlong %lld\n", (vlong)(((vlong)(s7))));
	fprint(1, "8 int32 %lld\n", (vlong)(((long)(s8))));
	fprint(1, "9 uint8 %lld\n", (vlong)(((uchar)(s9))));
	fprint(1, "10 char %lld\n", (vlong)(((char)(s10))));
	fprint(1, "11 bool %lld\n", (vlong)(((s11) != 0)));
	fprint(1, "12 uint %lld\n", (vlong)(((uint)(s12))));
	fprint(1, "13 int8 %lld\n", (vlong)(((char)(s13))));
	fprint(1, "14 short %lld\n", (vlong)(((short)(s14))));
	fprint(1, "15 int64 %lld\n", (vlong)(((vlong)(s15))));
	fprint(1, "16 ulong %lld\n", (vlong)(((ulong)(s16))));
	fprint(1, "17 uvlong %lld\n", (vlong)(((uvlong)(s17))));
	fprint(1, "18 uint32 %lld\n", (vlong)(((ulong)(s18))));
	fprint(1, "19 uchar %lld\n", (vlong)(((uchar)(s19))));
	fprint(1, "20 int16 %lld\n", (vlong)(((short)(s20))));
	fprint(1, "21 intptr %lld\n", (vlong)(((intptr)(s21))));
	exits(nil);
}
