/* generated by tools/o9prop.py kind=width seed=4689670 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong s0 = 65536;
	vlong s1 = -32769;
	vlong s2 = 1;
	vlong s3 = 32768;
	vlong s4 = 127;
	vlong s5 = 1;
	vlong s6 = 65535;
	vlong s7 = -128;
	vlong s8 = 31;
	vlong s9 = 128;
	vlong s10 = -257;
	vlong s11 = 0;
	vlong s12 = -32769;
	vlong s13 = 127;
	vlong s14 = 32767;
	vlong s15 = -65537;
	vlong s16 = 63;
	vlong s17 = -32768;
	vlong s18 = 1;
	vlong s19 = 127;
	vlong s20 = 127;
	vlong s21 = 7;
	USED(s0); USED(s1); USED(s2); USED(s3); USED(s4); USED(s5); USED(s6); USED(s7); USED(s8); USED(s9); USED(s10); USED(s11); USED(s12); USED(s13); USED(s14); USED(s15); USED(s16); USED(s17); USED(s18); USED(s19); USED(s20); USED(s21);
	fprint(1, "vars %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n", s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21);
	fprint(1, "0 uchar %lld\n", (vlong)(((uchar)(s0))));
	fprint(1, "1 uint8 %lld\n", (vlong)(((uchar)(s1))));
	fprint(1, "2 int %lld\n", (vlong)(((int)(s2))));
	fprint(1, "3 uint16 %lld\n", (vlong)(((ushort)(s3))));
	fprint(1, "4 uintptr %lld\n", (vlong)(((uintptr)(s4))));
	fprint(1, "5 uvlong %lld\n", (vlong)(((uvlong)(s5))));
	fprint(1, "6 char %lld\n", (vlong)(((char)(s6))));
	fprint(1, "7 int8 %lld\n", (vlong)(((char)(s7))));
	fprint(1, "8 uint32 %lld\n", (vlong)(((ulong)(s8))));
	fprint(1, "9 int16 %lld\n", (vlong)(((short)(s9))));
	fprint(1, "10 uint %lld\n", (vlong)(((uint)(s10))));
	fprint(1, "11 long %lld\n", (vlong)(((long)(s11))));
	fprint(1, "12 ushort %lld\n", (vlong)(((ushort)(s12))));
	fprint(1, "13 int32 %lld\n", (vlong)(((long)(s13))));
	fprint(1, "14 short %lld\n", (vlong)(((short)(s14))));
	fprint(1, "15 ulong %lld\n", (vlong)(((ulong)(s15))));
	fprint(1, "16 int64 %lld\n", (vlong)(((vlong)(s16))));
	fprint(1, "17 vlong %lld\n", (vlong)(((vlong)(s17))));
	fprint(1, "18 byte %lld\n", (vlong)(((uchar)(s18))));
	fprint(1, "19 uint64 %lld\n", (vlong)(((uvlong)(s19))));
	fprint(1, "20 intptr %lld\n", (vlong)(((intptr)(s20))));
	fprint(1, "21 bool %lld\n", (vlong)(((s21) != 0)));
	exits(nil);
}
