/* generated by tools/o9prop.py kind=width seed=966752004 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong s0 = -128;
	vlong s1 = 63;
	vlong s2 = 1;
	vlong s3 = -257;
	vlong s4 = 0;
	vlong s5 = -32768;
	vlong s6 = 256;
	vlong s7 = 1;
	vlong s8 = -65537;
	vlong s9 = -256;
	vlong s10 = 256;
	vlong s11 = 65536;
	vlong s12 = 128;
	vlong s13 = 1023;
	vlong s14 = 7;
	vlong s15 = 1;
	vlong s16 = 255;
	vlong s17 = -65537;
	vlong s18 = 65536;
	vlong s19 = -257;
	vlong s20 = 65535;
	vlong s21 = 15;
	USED(s0); USED(s1); USED(s2); USED(s3); USED(s4); USED(s5); USED(s6); USED(s7); USED(s8); USED(s9); USED(s10); USED(s11); USED(s12); USED(s13); USED(s14); USED(s15); USED(s16); USED(s17); USED(s18); USED(s19); USED(s20); USED(s21);
	fprint(1, "vars %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n", s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21);
	fprint(1, "0 int32 %lld\n", (vlong)(((long)(s0))));
	fprint(1, "1 uchar %lld\n", (vlong)(((uchar)(s1))));
	fprint(1, "2 bool %lld\n", (vlong)(((s2) != 0)));
	fprint(1, "3 uint16 %lld\n", (vlong)(((ushort)(s3))));
	fprint(1, "4 uvlong %lld\n", (vlong)(((uvlong)(s4))));
	fprint(1, "5 vlong %lld\n", (vlong)(((vlong)(s5))));
	fprint(1, "6 byte %lld\n", (vlong)(((uchar)(s6))));
	fprint(1, "7 int16 %lld\n", (vlong)(((short)(s7))));
	fprint(1, "8 short %lld\n", (vlong)(((short)(s8))));
	fprint(1, "9 long %lld\n", (vlong)(((long)(s9))));
	fprint(1, "10 int %lld\n", (vlong)(((int)(s10))));
	fprint(1, "11 ushort %lld\n", (vlong)(((ushort)(s11))));
	fprint(1, "12 int8 %lld\n", (vlong)(((char)(s12))));
	fprint(1, "13 ulong %lld\n", (vlong)(((ulong)(s13))));
	fprint(1, "14 uint32 %lld\n", (vlong)(((ulong)(s14))));
	fprint(1, "15 intptr %lld\n", (vlong)(((intptr)(s15))));
	fprint(1, "16 uint64 %lld\n", (vlong)(((uvlong)(s16))));
	fprint(1, "17 uint8 %lld\n", (vlong)(((uchar)(s17))));
	fprint(1, "18 uint %lld\n", (vlong)(((uint)(s18))));
	fprint(1, "19 int64 %lld\n", (vlong)(((vlong)(s19))));
	fprint(1, "20 char %lld\n", (vlong)(((char)(s20))));
	fprint(1, "21 uintptr %lld\n", (vlong)(((uintptr)(s21))));
	exits(nil);
}
