/* generated by tools/o9prop.py kind=width seed=812271910 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong s0 = 15;
	vlong s1 = -1;
	vlong s2 = 0;
	vlong s3 = 0;
	vlong s4 = 1;
	vlong s5 = 63;
	vlong s6 = 31;
	vlong s7 = 2;
	vlong s8 = 64;
	vlong s9 = 64;
	vlong s10 = -65537;
	vlong s11 = 7;
	vlong s12 = 0;
	vlong s13 = -256;
	vlong s14 = 2;
	vlong s15 = 64;
	vlong s16 = 31;
	vlong s17 = -257;
	vlong s18 = -32769;
	vlong s19 = -256;
	vlong s20 = 128;
	vlong s21 = 32768;
	USED(s0); USED(s1); USED(s2); USED(s3); USED(s4); USED(s5); USED(s6); USED(s7); USED(s8); USED(s9); USED(s10); USED(s11); USED(s12); USED(s13); USED(s14); USED(s15); USED(s16); USED(s17); USED(s18); USED(s19); USED(s20); USED(s21);
	fprint(1, "vars %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n", s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21);
	fprint(1, "0 int16 %lld\n", (vlong)(((short)(s0))));
	fprint(1, "1 uint32 %lld\n", (vlong)(((ulong)(s1))));
	fprint(1, "2 short %lld\n", (vlong)(((short)(s2))));
	fprint(1, "3 ushort %lld\n", (vlong)(((ushort)(s3))));
	fprint(1, "4 uintptr %lld\n", (vlong)(((uintptr)(s4))));
	fprint(1, "5 int32 %lld\n", (vlong)(((long)(s5))));
	fprint(1, "6 uint16 %lld\n", (vlong)(((ushort)(s6))));
	fprint(1, "7 uint64 %lld\n", (vlong)(((uvlong)(s7))));
	fprint(1, "8 uint8 %lld\n", (vlong)(((uchar)(s8))));
	fprint(1, "9 uvlong %lld\n", (vlong)(((uvlong)(s9))));
	fprint(1, "10 intptr %lld\n", (vlong)(((intptr)(s10))));
	fprint(1, "11 bool %lld\n", (vlong)(((s11) != 0)));
	fprint(1, "12 vlong %lld\n", (vlong)(((vlong)(s12))));
	fprint(1, "13 long %lld\n", (vlong)(((long)(s13))));
	fprint(1, "14 int8 %lld\n", (vlong)(((char)(s14))));
	fprint(1, "15 uchar %lld\n", (vlong)(((uchar)(s15))));
	fprint(1, "16 int64 %lld\n", (vlong)(((vlong)(s16))));
	fprint(1, "17 int %lld\n", (vlong)(((int)(s17))));
	fprint(1, "18 ulong %lld\n", (vlong)(((ulong)(s18))));
	fprint(1, "19 uint %lld\n", (vlong)(((uint)(s19))));
	fprint(1, "20 char %lld\n", (vlong)(((char)(s20))));
	fprint(1, "21 byte %lld\n", (vlong)(((uchar)(s21))));
	exits(nil);
}
