/* generated by tools/o9prop.py kind=width seed=1444934597 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong s0 = 1;
	vlong s1 = 1023;
	vlong s2 = -129;
	vlong s3 = -65536;
	vlong s4 = 65535;
	vlong s5 = 255;
	vlong s6 = -65537;
	vlong s7 = -65537;
	vlong s8 = 2;
	vlong s9 = -65537;
	vlong s10 = 31;
	vlong s11 = 256;
	vlong s12 = -1;
	vlong s13 = 255;
	vlong s14 = 127;
	vlong s15 = 1;
	vlong s16 = 65535;
	vlong s17 = -256;
	vlong s18 = -256;
	vlong s19 = 255;
	vlong s20 = 63;
	vlong s21 = 64;
	USED(s0); USED(s1); USED(s2); USED(s3); USED(s4); USED(s5); USED(s6); USED(s7); USED(s8); USED(s9); USED(s10); USED(s11); USED(s12); USED(s13); USED(s14); USED(s15); USED(s16); USED(s17); USED(s18); USED(s19); USED(s20); USED(s21);
	fprint(1, "vars %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n", s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21);
	fprint(1, "0 uint32 %lld\n", (vlong)(((ulong)(s0))));
	fprint(1, "1 int32 %lld\n", (vlong)(((long)(s1))));
	fprint(1, "2 vlong %lld\n", (vlong)(((vlong)(s2))));
	fprint(1, "3 intptr %lld\n", (vlong)(((intptr)(s3))));
	fprint(1, "4 uint %lld\n", (vlong)(((uint)(s4))));
	fprint(1, "5 int %lld\n", (vlong)(((int)(s5))));
	fprint(1, "6 uint16 %lld\n", (vlong)(((ushort)(s6))));
	fprint(1, "7 bool %lld\n", (vlong)(((s7) != 0)));
	fprint(1, "8 int64 %lld\n", (vlong)(((vlong)(s8))));
	fprint(1, "9 char %lld\n", (vlong)(((char)(s9))));
	fprint(1, "10 uint64 %lld\n", (vlong)(((uvlong)(s10))));
	fprint(1, "11 int16 %lld\n", (vlong)(((short)(s11))));
	fprint(1, "12 long %lld\n", (vlong)(((long)(s12))));
	fprint(1, "13 uintptr %lld\n", (vlong)(((uintptr)(s13))));
	fprint(1, "14 uchar %lld\n", (vlong)(((uchar)(s14))));
	fprint(1, "15 uint8 %lld\n", (vlong)(((uchar)(s15))));
	fprint(1, "16 ulong %lld\n", (vlong)(((ulong)(s16))));
	fprint(1, "17 short %lld\n", (vlong)(((short)(s17))));
	fprint(1, "18 ushort %lld\n", (vlong)(((ushort)(s18))));
	fprint(1, "19 int8 %lld\n", (vlong)(((char)(s19))));
	fprint(1, "20 uvlong %lld\n", (vlong)(((uvlong)(s20))));
	fprint(1, "21 byte %lld\n", (vlong)(((uchar)(s21))));
	exits(nil);
}
