/* generated by tools/o9prop.py kind=width seed=803674399 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong s0 = 255;
	vlong s1 = 7;
	vlong s2 = 32767;
	vlong s3 = 0;
	vlong s4 = 63;
	vlong s5 = 32768;
	vlong s6 = 65536;
	vlong s7 = 1;
	vlong s8 = -65536;
	vlong s9 = 7;
	vlong s10 = 31;
	vlong s11 = 1023;
	vlong s12 = 15;
	vlong s13 = 127;
	vlong s14 = 1023;
	vlong s15 = -256;
	vlong s16 = 255;
	vlong s17 = 0;
	vlong s18 = -257;
	vlong s19 = -129;
	vlong s20 = -128;
	vlong s21 = 1023;
	USED(s0); USED(s1); USED(s2); USED(s3); USED(s4); USED(s5); USED(s6); USED(s7); USED(s8); USED(s9); USED(s10); USED(s11); USED(s12); USED(s13); USED(s14); USED(s15); USED(s16); USED(s17); USED(s18); USED(s19); USED(s20); USED(s21);
	fprint(1, "vars %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n", s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21);
	fprint(1, "0 long %lld\n", (vlong)(((long)(s0))));
	fprint(1, "1 char %lld\n", (vlong)(((char)(s1))));
	fprint(1, "2 int32 %lld\n", (vlong)(((long)(s2))));
	fprint(1, "3 int16 %lld\n", (vlong)(((short)(s3))));
	fprint(1, "4 short %lld\n", (vlong)(((short)(s4))));
	fprint(1, "5 byte %lld\n", (vlong)(((uchar)(s5))));
	fprint(1, "6 ulong %lld\n", (vlong)(((ulong)(s6))));
	fprint(1, "7 int64 %lld\n", (vlong)(((vlong)(s7))));
	fprint(1, "8 uint8 %lld\n", (vlong)(((uchar)(s8))));
	fprint(1, "9 uint64 %lld\n", (vlong)(((uvlong)(s9))));
	fprint(1, "10 bool %lld\n", (vlong)(((s10) != 0)));
	fprint(1, "11 uchar %lld\n", (vlong)(((uchar)(s11))));
	fprint(1, "12 uvlong %lld\n", (vlong)(((uvlong)(s12))));
	fprint(1, "13 uint16 %lld\n", (vlong)(((ushort)(s13))));
	fprint(1, "14 intptr %lld\n", (vlong)(((intptr)(s14))));
	fprint(1, "15 vlong %lld\n", (vlong)(((vlong)(s15))));
	fprint(1, "16 uint %lld\n", (vlong)(((uint)(s16))));
	fprint(1, "17 ushort %lld\n", (vlong)(((ushort)(s17))));
	fprint(1, "18 uint32 %lld\n", (vlong)(((ulong)(s18))));
	fprint(1, "19 int8 %lld\n", (vlong)(((char)(s19))));
	fprint(1, "20 int %lld\n", (vlong)(((int)(s20))));
	fprint(1, "21 uintptr %lld\n", (vlong)(((uintptr)(s21))));
	exits(nil);
}
