/* generated by tools/o9prop.py kind=width seed=1497472205 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong s0 = 32768;
	vlong s1 = 15;
	vlong s2 = -129;
	vlong s3 = 127;
	vlong s4 = 65536;
	vlong s5 = 64;
	vlong s6 = 256;
	vlong s7 = 32767;
	vlong s8 = 63;
	vlong s9 = 63;
	vlong s10 = 7;
	vlong s11 = 127;
	vlong s12 = 0;
	vlong s13 = 65535;
	vlong s14 = -256;
	vlong s15 = -32768;
	vlong s16 = -129;
	vlong s17 = 255;
	vlong s18 = 31;
	vlong s19 = 65535;
	vlong s20 = -129;
	vlong s21 = 128;
	USED(s0); USED(s1); USED(s2); USED(s3); USED(s4); USED(s5); USED(s6); USED(s7); USED(s8); USED(s9); USED(s10); USED(s11); USED(s12); USED(s13); USED(s14); USED(s15); USED(s16); USED(s17); USED(s18); USED(s19); USED(s20); USED(s21);
	fprint(1, "vars %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n", s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21);
	fprint(1, "0 int8 %lld\n", (vlong)(((char)(s0))));
	fprint(1, "1 vlong %lld\n", (vlong)(((vlong)(s1))));
	fprint(1, "2 bool %lld\n", (vlong)(((s2) != 0)));
	fprint(1, "3 uint64 %lld\n", (vlong)(((uvlong)(s3))));
	fprint(1, "4 uintptr %lld\n", (vlong)(((uintptr)(s4))));
	fprint(1, "5 uint16 %lld\n", (vlong)(((ushort)(s5))));
	fprint(1, "6 uchar %lld\n", (vlong)(((uchar)(s6))));
	fprint(1, "7 int64 %lld\n", (vlong)(((vlong)(s7))));
	fprint(1, "8 short %lld\n", (vlong)(((short)(s8))));
	fprint(1, "9 char %lld\n", (vlong)(((char)(s9))));
	fprint(1, "10 uvlong %lld\n", (vlong)(((uvlong)(s10))));
	fprint(1, "11 ushort %lld\n", (vlong)(((ushort)(s11))));
	fprint(1, "12 uint8 %lld\n", (vlong)(((uchar)(s12))));
	fprint(1, "13 int32 %lld\n", (vlong)(((long)(s13))));
	fprint(1, "14 intptr %lld\n", (vlong)(((intptr)(s14))));
	fprint(1, "15 int %lld\n", (vlong)(((int)(s15))));
	fprint(1, "16 long %lld\n", (vlong)(((long)(s16))));
	fprint(1, "17 int16 %lld\n", (vlong)(((short)(s17))));
	fprint(1, "18 ulong %lld\n", (vlong)(((ulong)(s18))));
	fprint(1, "19 uint32 %lld\n", (vlong)(((ulong)(s19))));
	fprint(1, "20 uint %lld\n", (vlong)(((uint)(s20))));
	fprint(1, "21 byte %lld\n", (vlong)(((uchar)(s21))));
	exits(nil);
}
