/* generated by tools/o9prop.py kind=width seed=258992600 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong s0 = 65536;
	vlong s1 = 0;
	vlong s2 = 65535;
	vlong s3 = 128;
	vlong s4 = -129;
	vlong s5 = 32768;
	vlong s6 = 63;
	vlong s7 = -32769;
	vlong s8 = 15;
	vlong s9 = -32769;
	vlong s10 = 128;
	vlong s11 = 1;
	vlong s12 = 15;
	vlong s13 = 32767;
	vlong s14 = 2;
	vlong s15 = 127;
	vlong s16 = -129;
	vlong s17 = -128;
	vlong s18 = -65536;
	vlong s19 = 7;
	vlong s20 = 0;
	vlong s21 = -129;
	USED(s0); USED(s1); USED(s2); USED(s3); USED(s4); USED(s5); USED(s6); USED(s7); USED(s8); USED(s9); USED(s10); USED(s11); USED(s12); USED(s13); USED(s14); USED(s15); USED(s16); USED(s17); USED(s18); USED(s19); USED(s20); USED(s21);
	fprint(1, "vars %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n", s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21);
	fprint(1, "0 uvlong %lld\n", (vlong)(((uvlong)(s0))));
	fprint(1, "1 vlong %lld\n", (vlong)(((vlong)(s1))));
	fprint(1, "2 byte %lld\n", (vlong)(((uchar)(s2))));
	fprint(1, "3 bool %lld\n", (vlong)(((s3) != 0)));
	fprint(1, "4 uint8 %lld\n", (vlong)(((uchar)(s4))));
	fprint(1, "5 int32 %lld\n", (vlong)(((long)(s5))));
	fprint(1, "6 char %lld\n", (vlong)(((char)(s6))));
	fprint(1, "7 uchar %lld\n", (vlong)(((uchar)(s7))));
	fprint(1, "8 uint64 %lld\n", (vlong)(((uvlong)(s8))));
	fprint(1, "9 uint %lld\n", (vlong)(((uint)(s9))));
	fprint(1, "10 int8 %lld\n", (vlong)(((char)(s10))));
	fprint(1, "11 short %lld\n", (vlong)(((short)(s11))));
	fprint(1, "12 int16 %lld\n", (vlong)(((short)(s12))));
	fprint(1, "13 uint32 %lld\n", (vlong)(((ulong)(s13))));
	fprint(1, "14 ushort %lld\n", (vlong)(((ushort)(s14))));
	fprint(1, "15 uint16 %lld\n", (vlong)(((ushort)(s15))));
	fprint(1, "16 long %lld\n", (vlong)(((long)(s16))));
	fprint(1, "17 ulong %lld\n", (vlong)(((ulong)(s17))));
	fprint(1, "18 intptr %lld\n", (vlong)(((intptr)(s18))));
	fprint(1, "19 uintptr %lld\n", (vlong)(((uintptr)(s19))));
	fprint(1, "20 int %lld\n", (vlong)(((int)(s20))));
	fprint(1, "21 int64 %lld\n", (vlong)(((vlong)(s21))));
	exits(nil);
}
