/* generated by tools/o9prop.py kind=width seed=506553537 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong s0 = -128;
	vlong s1 = 1023;
	vlong s2 = -32768;
	vlong s3 = 0;
	vlong s4 = -65537;
	vlong s5 = 1;
	vlong s6 = 1023;
	vlong s7 = 32767;
	vlong s8 = 127;
	vlong s9 = 256;
	vlong s10 = -65536;
	vlong s11 = 64;
	vlong s12 = 31;
	vlong s13 = 0;
	vlong s14 = -65536;
	vlong s15 = -32768;
	vlong s16 = 1023;
	vlong s17 = -257;
	vlong s18 = 2;
	vlong s19 = 31;
	vlong s20 = 65536;
	vlong s21 = -257;
	USED(s0); USED(s1); USED(s2); USED(s3); USED(s4); USED(s5); USED(s6); USED(s7); USED(s8); USED(s9); USED(s10); USED(s11); USED(s12); USED(s13); USED(s14); USED(s15); USED(s16); USED(s17); USED(s18); USED(s19); USED(s20); USED(s21);
	fprint(1, "vars %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n", s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21);
	fprint(1, "0 byte %lld\n", (vlong)(((uchar)(s0))));
	fprint(1, "1 int32 %lld\n", (vlong)(((long)(s1))));
	fprint(1, "2 int %lld\n", (vlong)(((int)(s2))));
	fprint(1, "3 bool %lld\n", (vlong)(((s3) != 0)));
	fprint(1, "4 long %lld\n", (vlong)(((long)(s4))));
	fprint(1, "5 vlong %lld\n", (vlong)(((vlong)(s5))));
	fprint(1, "6 uint8 %lld\n", (vlong)(((uchar)(s6))));
	fprint(1, "7 uint64 %lld\n", (vlong)(((uvlong)(s7))));
	fprint(1, "8 ulong %lld\n", (vlong)(((ulong)(s8))));
	fprint(1, "9 uint %lld\n", (vlong)(((uint)(s9))));
	fprint(1, "10 uchar %lld\n", (vlong)(((uchar)(s10))));
	fprint(1, "11 uintptr %lld\n", (vlong)(((uintptr)(s11))));
	fprint(1, "12 int64 %lld\n", (vlong)(((vlong)(s12))));
	fprint(1, "13 uvlong %lld\n", (vlong)(((uvlong)(s13))));
	fprint(1, "14 int8 %lld\n", (vlong)(((char)(s14))));
	fprint(1, "15 ushort %lld\n", (vlong)(((ushort)(s15))));
	fprint(1, "16 uint16 %lld\n", (vlong)(((ushort)(s16))));
	fprint(1, "17 intptr %lld\n", (vlong)(((intptr)(s17))));
	fprint(1, "18 short %lld\n", (vlong)(((short)(s18))));
	fprint(1, "19 int16 %lld\n", (vlong)(((short)(s19))));
	fprint(1, "20 uint32 %lld\n", (vlong)(((ulong)(s20))));
	fprint(1, "21 char %lld\n", (vlong)(((char)(s21))));
	exits(nil);
}
