/* generated by tools/o9prop.py kind=width seed=1158376406 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong s0 = 32767;
	vlong s1 = 128;
	vlong s2 = -32768;
	vlong s3 = 15;
	vlong s4 = 32767;
	vlong s5 = 7;
	vlong s6 = 32768;
	vlong s7 = 128;
	vlong s8 = -256;
	vlong s9 = -32769;
	vlong s10 = 1023;
	vlong s11 = -32768;
	vlong s12 = 1023;
	vlong s13 = -256;
	vlong s14 = 128;
	vlong s15 = 256;
	vlong s16 = -129;
	vlong s17 = 32768;
	vlong s18 = 7;
	vlong s19 = 65536;
	vlong s20 = 65535;
	vlong s21 = 32767;
	USED(s0); USED(s1); USED(s2); USED(s3); USED(s4); USED(s5); USED(s6); USED(s7); USED(s8); USED(s9); USED(s10); USED(s11); USED(s12); USED(s13); USED(s14); USED(s15); USED(s16); USED(s17); USED(s18); USED(s19); USED(s20); USED(s21);
	fprint(1, "vars %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n", s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21);
	fprint(1, "0 short %lld\n", (vlong)(((short)(s0))));
	fprint(1, "1 uintptr %lld\n", (vlong)(((uintptr)(s1))));
	fprint(1, "2 int %lld\n", (vlong)(((int)(s2))));
	fprint(1, "3 char %lld\n", (vlong)(((char)(s3))));
	fprint(1, "4 ulong %lld\n", (vlong)(((ulong)(s4))));
	fprint(1, "5 uint32 %lld\n", (vlong)(((ulong)(s5))));
	fprint(1, "6 byte %lld\n", (vlong)(((uchar)(s6))));
	fprint(1, "7 uchar %lld\n", (vlong)(((uchar)(s7))));
	fprint(1, "8 intptr %lld\n", (vlong)(((intptr)(s8))));
	fprint(1, "9 uint8 %lld\n", (vlong)(((uchar)(s9))));
	fprint(1, "10 uint %lld\n", (vlong)(((uint)(s10))));
	fprint(1, "11 int32 %lld\n", (vlong)(((long)(s11))));
	fprint(1, "12 uint16 %lld\n", (vlong)(((ushort)(s12))));
	fprint(1, "13 ushort %lld\n", (vlong)(((ushort)(s13))));
	fprint(1, "14 vlong %lld\n", (vlong)(((vlong)(s14))));
	fprint(1, "15 uint64 %lld\n", (vlong)(((uvlong)(s15))));
	fprint(1, "16 int16 %lld\n", (vlong)(((short)(s16))));
	fprint(1, "17 long %lld\n", (vlong)(((long)(s17))));
	fprint(1, "18 uvlong %lld\n", (vlong)(((uvlong)(s18))));
	fprint(1, "19 bool %lld\n", (vlong)(((s19) != 0)));
	fprint(1, "20 int8 %lld\n", (vlong)(((char)(s20))));
	fprint(1, "21 int64 %lld\n", (vlong)(((vlong)(s21))));
	exits(nil);
}
