/* generated by tools/o9prop.py kind=width seed=1995856918 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong s0 = 255;
	vlong s1 = 128;
	vlong s2 = 32767;
	vlong s3 = -32769;
	vlong s4 = -128;
	vlong s5 = -256;
	vlong s6 = 7;
	vlong s7 = -1;
	vlong s8 = -257;
	vlong s9 = -32769;
	vlong s10 = 32768;
	vlong s11 = 2;
	vlong s12 = 65535;
	vlong s13 = 31;
	vlong s14 = 256;
	vlong s15 = -129;
	vlong s16 = -256;
	vlong s17 = 32768;
	vlong s18 = 127;
	vlong s19 = 65536;
	vlong s20 = 0;
	vlong s21 = -256;
	USED(s0); USED(s1); USED(s2); USED(s3); USED(s4); USED(s5); USED(s6); USED(s7); USED(s8); USED(s9); USED(s10); USED(s11); USED(s12); USED(s13); USED(s14); USED(s15); USED(s16); USED(s17); USED(s18); USED(s19); USED(s20); USED(s21);
	fprint(1, "vars %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n", s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21);
	fprint(1, "0 uvlong %lld\n", (vlong)(((uvlong)(s0))));
	fprint(1, "1 int32 %lld\n", (vlong)(((long)(s1))));
	fprint(1, "2 byte %lld\n", (vlong)(((uchar)(s2))));
	fprint(1, "3 int8 %lld\n", (vlong)(((char)(s3))));
	fprint(1, "4 uchar %lld\n", (vlong)(((uchar)(s4))));
	fprint(1, "5 char %lld\n", (vlong)(((char)(s5))));
	fprint(1, "6 int %lld\n", (vlong)(((int)(s6))));
	fprint(1, "7 short %lld\n", (vlong)(((short)(s7))));
	fprint(1, "8 int16 %lld\n", (vlong)(((short)(s8))));
	fprint(1, "9 uint8 %lld\n", (vlong)(((uchar)(s9))));
	fprint(1, "10 uint16 %lld\n", (vlong)(((ushort)(s10))));
	fprint(1, "11 vlong %lld\n", (vlong)(((vlong)(s11))));
	fprint(1, "12 uint64 %lld\n", (vlong)(((uvlong)(s12))));
	fprint(1, "13 bool %lld\n", (vlong)(((s13) != 0)));
	fprint(1, "14 ushort %lld\n", (vlong)(((ushort)(s14))));
	fprint(1, "15 int64 %lld\n", (vlong)(((vlong)(s15))));
	fprint(1, "16 intptr %lld\n", (vlong)(((intptr)(s16))));
	fprint(1, "17 uint32 %lld\n", (vlong)(((ulong)(s17))));
	fprint(1, "18 uint %lld\n", (vlong)(((uint)(s18))));
	fprint(1, "19 long %lld\n", (vlong)(((long)(s19))));
	fprint(1, "20 uintptr %lld\n", (vlong)(((uintptr)(s20))));
	fprint(1, "21 ulong %lld\n", (vlong)(((ulong)(s21))));
	exits(nil);
}
