/* generated by tools/o9prop.py kind=width seed=816047026 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong s0 = 32768;
	vlong s1 = 15;
	vlong s2 = 63;
	vlong s3 = 65536;
	vlong s4 = -256;
	vlong s5 = 65536;
	vlong s6 = -256;
	vlong s7 = -1;
	vlong s8 = 65536;
	vlong s9 = 2;
	vlong s10 = 65535;
	vlong s11 = -65536;
	vlong s12 = 32768;
	vlong s13 = -129;
	vlong s14 = 255;
	vlong s15 = -32769;
	vlong s16 = 63;
	vlong s17 = -65537;
	vlong s18 = 64;
	vlong s19 = 1023;
	vlong s20 = 1;
	vlong s21 = 65536;
	USED(s0); USED(s1); USED(s2); USED(s3); USED(s4); USED(s5); USED(s6); USED(s7); USED(s8); USED(s9); USED(s10); USED(s11); USED(s12); USED(s13); USED(s14); USED(s15); USED(s16); USED(s17); USED(s18); USED(s19); USED(s20); USED(s21);
	fprint(1, "vars %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld %lld\n", s0, s1, s2, s3, s4, s5, s6, s7, s8, s9, s10, s11, s12, s13, s14, s15, s16, s17, s18, s19, s20, s21);
	fprint(1, "0 uint64 %lld\n", (vlong)(((uvlong)(s0))));
	fprint(1, "1 uintptr %lld\n", (vlong)(((uintptr)(s1))));
	fprint(1, "2 uint16 %lld\n", (vlong)(((ushort)(s2))));
	fprint(1, "3 ulong %lld\n", (vlong)(((ulong)(s3))));
	fprint(1, "4 vlong %lld\n", (vlong)(((vlong)(s4))));
	fprint(1, "5 uint8 %lld\n", (vlong)(((uchar)(s5))));
	fprint(1, "6 long %lld\n", (vlong)(((long)(s6))));
	fprint(1, "7 int16 %lld\n", (vlong)(((short)(s7))));
	fprint(1, "8 char %lld\n", (vlong)(((char)(s8))));
	fprint(1, "9 byte %lld\n", (vlong)(((uchar)(s9))));
	fprint(1, "10 uint %lld\n", (vlong)(((uint)(s10))));
	fprint(1, "11 int32 %lld\n", (vlong)(((long)(s11))));
	fprint(1, "12 uint32 %lld\n", (vlong)(((ulong)(s12))));
	fprint(1, "13 short %lld\n", (vlong)(((short)(s13))));
	fprint(1, "14 intptr %lld\n", (vlong)(((intptr)(s14))));
	fprint(1, "15 int8 %lld\n", (vlong)(((char)(s15))));
	fprint(1, "16 uvlong %lld\n", (vlong)(((uvlong)(s16))));
	fprint(1, "17 int %lld\n", (vlong)(((int)(s17))));
	fprint(1, "18 uchar %lld\n", (vlong)(((uchar)(s18))));
	fprint(1, "19 ushort %lld\n", (vlong)(((ushort)(s19))));
	fprint(1, "20 int64 %lld\n", (vlong)(((vlong)(s20))));
	fprint(1, "21 bool %lld\n", (vlong)(((s21) != 0)));
	exits(nil);
}
