/* generated by tools/o9prop.py kind=stdlib seed=1646747202 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	fprint(1, "list 3 40 60 28 128\ndict 1 0 40 60\nnames tabula draw\n");
	exits(nil);
}
