/* generated by tools/o9prop.py kind=stdlib seed=1868813816 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	fprint(1, "list 3 15 90 44 149\ndict 1 0 15 90\nnames grid beta\n");
	exits(nil);
}
