/* generated by tools/o9prop.py kind=stdlib seed=937464482 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	fprint(1, "list 3 39 71 21 131\ndict 1 0 39 71\nnames draw tabula\n");
	exits(nil);
}
