/* generated by tools/o9prop.py kind=stdlib seed=369827335 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	fprint(1, "list 3 42 94 28 164\ndict 1 0 42 94\nnames tabula grid\n");
	exits(nil);
}
