/* generated by tools/o9prop.py kind=stdlib seed=794570675 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	fprint(1, "list 3 43 95 41 179\ndict 1 0 43 95\nnames grid alpha\n");
	exits(nil);
}
