/* generated by tools/o9prop.py kind=stdlib seed=1288656596 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	fprint(1, "len 20\ntrim tabula grid draw\nslice tabula\ncontains 1 0\nlast 9 count 1\nprefix 1 suffix 1\ncase   tabula grid draw   |   TABULA GRID DRAW  \ncat   tabula grid draw  !\nreplace   tabula front draw  \nrepeat tata\nfield grid missing \nbefore tabula after grid,draw\nline grid\n");
	exits(nil);
}
