/* generated by tools/o9prop.py kind=stdlib seed=816837685 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	fprint(1, "len 20\ntrim rio tabula alpha\nslice rio \ncontains 1 0\nlast 6 count 1\nprefix 1 suffix 1\ncase   rio tabula alpha   |   RIO TABULA ALPHA  \ncat   rio tabula alpha  !\nreplace   rio orders alpha  \nrepeat riri\nfield tabula missing \nbefore rio after tabula,alpha\nline tabula\n");
	exits(nil);
}
