/* generated by tools/o9prop.py kind=stdlib seed=1950624349 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	fprint(1, "len 19\ntrim orders beta rio\nslice rd\ncontains 1 0\nlast 9 count 1\nprefix 1 suffix 1\ncase   orders beta rio   |   ORDERS BETA RIO  \ncat   orders beta rio  !\nreplace   orders front rio  \nrepeat oror\nfield beta missing \nbefore orders after beta,rio\nline beta\n");
	exits(nil);
}
