/* generated by tools/o9prop.py kind=stdlib seed=1338938392 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	fprint(1, "len 21\ntrim alpha orders beta\nslice alpha \ncontains 1 0\nlast 8 count 1\nprefix 1 suffix 1\ncase   alpha orders beta   |   ALPHA ORDERS BETA  \ncat   alpha orders beta  !\nreplace   alpha grid beta  \nrepeat alal\nfield orders missing \nbefore alpha after orders,beta\nline orders\n");
	exits(nil);
}
