/* generated by tools/o9prop.py kind=stdlib seed=1120331296 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	fprint(1, "len 23\ntrim tabula orders front\nslice   \ncontains 1 0\nlast 9 count 1\nprefix 1 suffix 1\ncase   tabula orders front   |   TABULA ORDERS FRONT  \ncat   tabula orders front  !\nreplace   tabula alpha front  \nrepeat tatatata\nfield orders missing \nbefore tabula after orders,front\nline orders\n");
	exits(nil);
}
