/* generated by tools/o9prop.py kind=stdlib seed=1465026936 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	fprint(1, "schema orders has 1 missing 0\npaid 1 rio 7\nreadcmp 0\nbad -1\nopen 1 draw\n");
	exits(nil);
}
