/* generated by tools/o9prop.py seed=1406996370 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 43;
	vlong b = -1;
	vlong d = -57;
	int p = 1;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((0 - (-6))));
	fprint(1, "1 %lld\n", (vlong)(((11 << 1) % 13)));
	fprint(1, "2 %lld\n", (vlong)(((~(d * 9)) ^ ((~d) + (d - -142)))));
	fprint(1, "3 %lld\n", (vlong)((~(5 >> 3))));
	fprint(1, "4 %lld\n", (vlong)((((d >= d) || (3 <= 3)) || ((a + -9) > (10 << 5)))));
	fprint(1, "5 %lld\n", (vlong)((1 == -5)));
	fprint(1, "6 %lld\n", (vlong)((((!q) && (p != p)) == ((1 || 1) || (!0)))));
	fprint(1, "7 %lld\n", (vlong)((!q)));
	exits(nil);
}
