/* generated by tools/o9prop.py seed=242587870 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = -16;
	vlong b = 1;
	vlong d = 9;
	int p = 0;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((13 % (2 + 7))));
	fprint(1, "1 %lld\n", (vlong)((((3 % (6 + 14)) ^ (~-1)) / 11)));
	fprint(1, "2 %lld\n", (vlong)(((-7 | d) * (a | d))));
	fprint(1, "3 %lld\n", (vlong)((14 << 1)));
	fprint(1, "4 %lld\n", (vlong)((!(!p))));
	fprint(1, "5 %lld\n", (vlong)((b == b)));
	fprint(1, "6 %lld\n", (vlong)(((!1) && (1 != 0))));
	fprint(1, "7 %lld\n", (vlong)((q && p)));
	exits(nil);
}
