/* generated by tools/o9prop.py seed=1342541599 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = -64;
	vlong b = 34;
	vlong d = -7;
	int p = 0;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((((b - -4) + (b - -12)) * (~(a * b)))));
	fprint(1, "1 %lld\n", (vlong)(((~b) - (146 | a))));
	fprint(1, "2 %lld\n", (vlong)(((15 % 11) >> 2)));
	fprint(1, "3 %lld\n", (vlong)(((b * 2) / (6 + 7))));
	fprint(1, "4 %lld\n", (vlong)((-3 >= 2)));
	fprint(1, "5 %lld\n", (vlong)((((0 << 3) - (8 << 0)) == ((3 % 12) | (3 ^ 6)))));
	fprint(1, "6 %lld\n", (vlong)((p || p)));
	fprint(1, "7 %lld\n", (vlong)(((p && q) && (q == 1))));
	exits(nil);
}
