/* generated by tools/o9prop.py seed=1367300475 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 4;
	vlong b = 14;
	vlong d = 60;
	int p = 0;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)(((6 / (7 + 13)) >> 5)));
	fprint(1, "1 %lld\n", (vlong)((0 - (b))));
	fprint(1, "2 %lld\n", (vlong)(((a + 15) >> 1)));
	fprint(1, "3 %lld\n", (vlong)((((14 / 12) - (~d)) & (0 - ((0 - (-5)))))));
	fprint(1, "4 %lld\n", (vlong)((1 != q)));
	fprint(1, "5 %lld\n", (vlong)((!(q != p))));
	fprint(1, "6 %lld\n", (vlong)((p && q)));
	fprint(1, "7 %lld\n", (vlong)((((-4 + -9) >> 1) != (0 - ((10 | -12))))));
	exits(nil);
}
