/* generated by tools/o9prop.py seed=342467373 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 56;
	vlong b = -52;
	vlong d = -29;
	int p = 1;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((161 - -17)));
	fprint(1, "1 %lld\n", (vlong)((-1 * -10)));
	fprint(1, "2 %lld\n", (vlong)((0 - (((a + d) / 1)))));
	fprint(1, "3 %lld\n", (vlong)((2 << 4)));
	fprint(1, "4 %lld\n", (vlong)((!((!0) == (!0)))));
	fprint(1, "5 %lld\n", (vlong)(((4 * a) <= (b * 12))));
	fprint(1, "6 %lld\n", (vlong)((!1)));
	fprint(1, "7 %lld\n", (vlong)((0 || q)));
	exits(nil);
}
