/* generated by tools/o9prop.py seed=464003545 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = -3;
	vlong b = 53;
	vlong d = -13;
	int p = 0;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)(((12 << 0) / (7 + 3))));
	fprint(1, "1 %lld\n", (vlong)((0 - ((2 - b)))));
	fprint(1, "2 %lld\n", (vlong)((((d ^ b) & (a ^ 71)) + ((b | 0) / 1))));
	fprint(1, "3 %lld\n", (vlong)(((5 << 2) >> 4)));
	fprint(1, "4 %lld\n", (vlong)(((q || p) && (0 == p))));
	fprint(1, "5 %lld\n", (vlong)((p && 0)));
	fprint(1, "6 %lld\n", (vlong)(((15 / 15) > (3 >> 3))));
	fprint(1, "7 %lld\n", (vlong)((!(!(!q)))));
	exits(nil);
}
