/* generated by tools/o9prop.py seed=1503772355 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 59;
	vlong b = -15;
	vlong d = 57;
	int p = 1;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((0 >> 3)));
	fprint(1, "1 %lld\n", (vlong)((~((b + -7) << 0))));
	fprint(1, "2 %lld\n", (vlong)(((-9 & 15) / (2 + 1))));
	fprint(1, "3 %lld\n", (vlong)((-134 | 5)));
	fprint(1, "4 %lld\n", (vlong)((!((1 && q) && (1 && 1)))));
	fprint(1, "5 %lld\n", (vlong)((((p || 1) || (!0)) == ((q != p) || (0 || p)))));
	fprint(1, "6 %lld\n", (vlong)((p || p)));
	fprint(1, "7 %lld\n", (vlong)((q != p)));
	exits(nil);
}
