/* generated by tools/o9prop.py seed=914447782 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 5;
	vlong b = 26;
	vlong d = -64;
	int p = 0;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((0 - ((~(5 / (5 + 2)))))));
	fprint(1, "1 %lld\n", (vlong)(((-8 | d) / 5)));
	fprint(1, "2 %lld\n", (vlong)(((~-5) & (0 << 2))));
	fprint(1, "3 %lld\n", (vlong)((((15 & -13) & (~10)) % 10)));
	fprint(1, "4 %lld\n", (vlong)((((0 != 0) || (!1)) && ((p == p) != (!q)))));
	fprint(1, "5 %lld\n", (vlong)((((a | d) ^ (11 >> 0)) >= ((-5 | 0) / 4))));
	fprint(1, "6 %lld\n", (vlong)((((7 << 0) < (0 - (11))) || ((-10 <= -3) || (-7 <= 7)))));
	fprint(1, "7 %lld\n", (vlong)((p == q)));
	exits(nil);
}
