/* generated by tools/o9prop.py seed=530578691 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = -25;
	vlong b = -55;
	vlong d = -35;
	int p = 1;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((((1 + 7) >> 1) ^ ((6 / 9) | (14 * -13)))));
	fprint(1, "1 %lld\n", (vlong)(((15 % 14) & (b - -135))));
	fprint(1, "2 %lld\n", (vlong)(((4 >> 4) >> 4)));
	fprint(1, "3 %lld\n", (vlong)((15 / (5 + 7))));
	fprint(1, "4 %lld\n", (vlong)(((p || 0) == (a <= d))));
	fprint(1, "5 %lld\n", (vlong)(((!(a > d)) && (!(0 != p)))));
	fprint(1, "6 %lld\n", (vlong)((((!0) && (!1)) || (!(p && q)))));
	fprint(1, "7 %lld\n", (vlong)((q != 1)));
	exits(nil);
}
