/* generated by tools/o9prop.py seed=652778949 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = -22;
	vlong b = -6;
	vlong d = 64;
	int p = 1;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((((a - d) ^ (15 / 9)) / 14)));
	fprint(1, "1 %lld\n", (vlong)((0 - (-12))));
	fprint(1, "2 %lld\n", (vlong)((((d * b) / (12 + 11)) * ((-15 * 13) >> 0))));
	fprint(1, "3 %lld\n", (vlong)((2 % 15)));
	fprint(1, "4 %lld\n", (vlong)((!q)));
	fprint(1, "5 %lld\n", (vlong)((q || 1)));
	fprint(1, "6 %lld\n", (vlong)((!0)));
	fprint(1, "7 %lld\n", (vlong)((p || 0)));
	exits(nil);
}
