/* generated by tools/o9prop.py seed=2028221602 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = -34;
	vlong b = -49;
	vlong d = 43;
	int p = 1;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)(((a | 85) & (b ^ b))));
	fprint(1, "1 %lld\n", (vlong)(((-15 | -5) / (9 + 5))));
	fprint(1, "2 %lld\n", (vlong)((~(-11 - d))));
	fprint(1, "3 %lld\n", (vlong)((((13 / (15 + 9)) * (-7 - 7)) / (10 + 13))));
	fprint(1, "4 %lld\n", (vlong)(((-13 - -2) != (4 / (6 + 10)))));
	fprint(1, "5 %lld\n", (vlong)(((-7 >= -2) || (1 && q))));
	fprint(1, "6 %lld\n", (vlong)((1 && p)));
	fprint(1, "7 %lld\n", (vlong)((((!q) && (p || p)) && ((1 != q) != (q != 0)))));
	exits(nil);
}
