/* generated by tools/o9prop.py seed=1355123948 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 64;
	vlong b = 45;
	vlong d = 54;
	int p = 0;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((1 >> 0)));
	fprint(1, "1 %lld\n", (vlong)((0 - (((~3) - (0 - (d)))))));
	fprint(1, "2 %lld\n", (vlong)((126 - d)));
	fprint(1, "3 %lld\n", (vlong)((0 - (4))));
	fprint(1, "4 %lld\n", (vlong)((q == p)));
	fprint(1, "5 %lld\n", (vlong)((!(!1))));
	fprint(1, "6 %lld\n", (vlong)((!(q != 0))));
	fprint(1, "7 %lld\n", (vlong)((((p || p) || (3 < -15)) != ((1 && p) || (q && 0)))));
	exits(nil);
}
