/* generated by tools/o9prop.py seed=365313452 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 28;
	vlong b = 27;
	vlong d = -16;
	int p = 1;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)(((~-9) & (14 / 9))));
	fprint(1, "1 %lld\n", (vlong)(((d + 140) & (5 << 5))));
	fprint(1, "2 %lld\n", (vlong)((15 >> 1)));
	fprint(1, "3 %lld\n", (vlong)((~15)));
	fprint(1, "4 %lld\n", (vlong)((!p)));
	fprint(1, "5 %lld\n", (vlong)(((1 == p) || (0 || p))));
	fprint(1, "6 %lld\n", (vlong)(((0 && 0) && (q && q))));
	fprint(1, "7 %lld\n", (vlong)(((!(!1)) && ((3 - 9) < (7 + 11)))));
	exits(nil);
}
