/* generated by tools/o9prop.py seed=602754294 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 3;
	vlong b = 6;
	vlong d = -37;
	int p = 0;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((((a ^ -186) - (~b)) - (~(d | 10)))));
	fprint(1, "1 %lld\n", (vlong)(((-1 ^ a) % 8)));
	fprint(1, "2 %lld\n", (vlong)((9 / (6 + 11))));
	fprint(1, "3 %lld\n", (vlong)((((-39 ^ -128) | (d | b)) - (0 - ((6 << 3))))));
	fprint(1, "4 %lld\n", (vlong)((1 != q)));
	fprint(1, "5 %lld\n", (vlong)(((p || 1) || (-9 <= b))));
	fprint(1, "6 %lld\n", (vlong)(((3 >> 4) == (6 << 2))));
	fprint(1, "7 %lld\n", (vlong)(((!(0 || 0)) || ((!p) || (q || 1)))));
	exits(nil);
}
