/* generated by tools/o9prop.py seed=994599755 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 26;
	vlong b = 37;
	vlong d = -8;
	int p = 0;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((5 * -15)));
	fprint(1, "1 %lld\n", (vlong)(((2 + -13) * (-8 | b))));
	fprint(1, "2 %lld\n", (vlong)((a * a)));
	fprint(1, "3 %lld\n", (vlong)((-144 - 128)));
	fprint(1, "4 %lld\n", (vlong)((((a * a) << 0) < ((d * 14) >> 0))));
	fprint(1, "5 %lld\n", (vlong)((2 <= 1)));
	fprint(1, "6 %lld\n", (vlong)((!p)));
	fprint(1, "7 %lld\n", (vlong)((((0 / 6) > (a + b)) && ((!p) != (1 || 0)))));
	exits(nil);
}
