/* generated by tools/o9prop.py seed=1701165987 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 34;
	vlong b = 20;
	vlong d = 3;
	int p = 1;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)(((11 << 2) ^ (a ^ b))));
	fprint(1, "1 %lld\n", (vlong)((((11 / 2) >> 1) % (10 + 14))));
	fprint(1, "2 %lld\n", (vlong)((4 / 13)));
	fprint(1, "3 %lld\n", (vlong)((~(~(9 >> 2)))));
	fprint(1, "4 %lld\n", (vlong)((!(q || p))));
	fprint(1, "5 %lld\n", (vlong)(((1 == q) != (p != q))));
	fprint(1, "6 %lld\n", (vlong)((0 && 0)));
	fprint(1, "7 %lld\n", (vlong)(((q == p) || (-10 <= d))));
	exits(nil);
}
