/* generated by tools/o9prop.py seed=1290507723 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 39;
	vlong b = -16;
	vlong d = 46;
	int p = 1;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)(((b & a) * (0 - (-9)))));
	fprint(1, "1 %lld\n", (vlong)(((14 << 5) << 3)));
	fprint(1, "2 %lld\n", (vlong)((b * d)));
	fprint(1, "3 %lld\n", (vlong)((b ^ b)));
	fprint(1, "4 %lld\n", (vlong)((((~0) | (1 - -8)) == ((d ^ -6) % (14 + 9)))));
	fprint(1, "5 %lld\n", (vlong)((0 != q)));
	fprint(1, "6 %lld\n", (vlong)((((q == 0) || (p || p)) || ((1 == q) && (!0)))));
	fprint(1, "7 %lld\n", (vlong)((!((q || 0) || (p || 0)))));
	exits(nil);
}
