/* generated by tools/o9prop.py seed=37366207 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 57;
	vlong b = -57;
	vlong d = 17;
	int p = 0;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((((12 / 3) / 9) + (0 - ((0 << 1))))));
	fprint(1, "1 %lld\n", (vlong)((0 - ((~-3)))));
	fprint(1, "2 %lld\n", (vlong)((((~-5) * (15 % (8 + 9))) / (14 + 12))));
	fprint(1, "3 %lld\n", (vlong)((112 | -55)));
	fprint(1, "4 %lld\n", (vlong)((((1 != q) == (p || p)) && (!(q || p)))));
	fprint(1, "5 %lld\n", (vlong)((!p)));
	fprint(1, "6 %lld\n", (vlong)((0 == p)));
	fprint(1, "7 %lld\n", (vlong)((!p)));
	exits(nil);
}
