/* generated by tools/o9prop.py seed=133663932 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 23;
	vlong b = -14;
	vlong d = 15;
	int p = 1;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((15 % (3 + 4))));
	fprint(1, "1 %lld\n", (vlong)((b & d)));
	fprint(1, "2 %lld\n", (vlong)(((-2 | 9) << 2)));
	fprint(1, "3 %lld\n", (vlong)((12 >> 1)));
	fprint(1, "4 %lld\n", (vlong)((!((5 - b) <= (9 / (11 + 11))))));
	fprint(1, "5 %lld\n", (vlong)(((q == p) == (!0))));
	fprint(1, "6 %lld\n", (vlong)((((!p) || (0 || q)) || ((0 - (a)) < (-14 | 5)))));
	fprint(1, "7 %lld\n", (vlong)(((p || p) || (0 && 1))));
	exits(nil);
}
