/* generated by tools/o9prop.py seed=1394673661 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 13;
	vlong b = 31;
	vlong d = 11;
	int p = 0;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((42 | 8)));
	fprint(1, "1 %lld\n", (vlong)((15 << 4)));
	fprint(1, "2 %lld\n", (vlong)((~(5 >> 4))));
	fprint(1, "3 %lld\n", (vlong)((0 - (((10 ^ d) + (3 >> 0))))));
	fprint(1, "4 %lld\n", (vlong)(((!0) && (2 > d))));
	fprint(1, "5 %lld\n", (vlong)(((-10 * -1) != (~0))));
	fprint(1, "6 %lld\n", (vlong)(((!(1 == q)) || ((3 - d) != (6 - 6)))));
	fprint(1, "7 %lld\n", (vlong)((((5 + 10) ^ (2 << 1)) >= ((0 | b) << 1))));
	exits(nil);
}
