/* generated by tools/o9prop.py seed=1394572671 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 39;
	vlong b = -31;
	vlong d = 10;
	int p = 0;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((~-11)));
	fprint(1, "1 %lld\n", (vlong)(((2 & -11) >> 0)));
	fprint(1, "2 %lld\n", (vlong)((((11 % (13 + 1)) >> 0) * ((0 % (2 + 10)) & (-11 & a)))));
	fprint(1, "3 %lld\n", (vlong)((((0 % 15) + (0 % (9 + 5))) & ((8 % (2 + 4)) % 7))));
	fprint(1, "4 %lld\n", (vlong)((q || p)));
	fprint(1, "5 %lld\n", (vlong)(((0 == p) != (b <= b))));
	fprint(1, "6 %lld\n", (vlong)(((4 >> 4) > (b - d))));
	fprint(1, "7 %lld\n", (vlong)((!p)));
	exits(nil);
}
