/* generated by tools/o9prop.py seed=1839264875 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = -8;
	vlong b = -55;
	vlong d = -17;
	int p = 0;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((0 - (4))));
	fprint(1, "1 %lld\n", (vlong)(((6 | 12) >> 1)));
	fprint(1, "2 %lld\n", (vlong)((((a & -188) - (a + -34)) - ((178 + 181) + (~a)))));
	fprint(1, "3 %lld\n", (vlong)((-61 - d)));
	fprint(1, "4 %lld\n", (vlong)(((1 && q) || (1 && q))));
	fprint(1, "5 %lld\n", (vlong)(((1 && 1) && (p && 0))));
	fprint(1, "6 %lld\n", (vlong)(((p == 0) == (b != d))));
	fprint(1, "7 %lld\n", (vlong)(((0 != 1) == (0 && 0))));
	exits(nil);
}
