/* generated by tools/o9prop.py seed=1962401461 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 21;
	vlong b = -44;
	vlong d = 48;
	int p = 0;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((a | a)));
	fprint(1, "1 %lld\n", (vlong)((149 | 83)));
	fprint(1, "2 %lld\n", (vlong)((~((5 / (13 + 1)) ^ (-15 ^ b)))));
	fprint(1, "3 %lld\n", (vlong)((0 - ((~a)))));
	fprint(1, "4 %lld\n", (vlong)((!((q || 1) || (-3 != a)))));
	fprint(1, "5 %lld\n", (vlong)((10 < 6)));
	fprint(1, "6 %lld\n", (vlong)((!((q || 0) != (b <= 14)))));
	fprint(1, "7 %lld\n", (vlong)((((13 >= a) || (q || q)) || ((-14 * -8) <= (3 << 0)))));
	exits(nil);
}
