/* generated by tools/o9prop.py seed=1606625401 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = -13;
	vlong b = -47;
	vlong d = -53;
	int p = 0;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((((6 & 7) % 2) + ((11 << 5) & (200 + -101)))));
	fprint(1, "1 %lld\n", (vlong)((b | 73)));
	fprint(1, "2 %lld\n", (vlong)((((b | 5) % (8 + 10)) >> 5)));
	fprint(1, "3 %lld\n", (vlong)((0 - (((-1 ^ -4) >> 2)))));
	fprint(1, "4 %lld\n", (vlong)((((b ^ d) >= (0 << 0)) || ((2 >> 5) >= (12 - -11)))));
	fprint(1, "5 %lld\n", (vlong)(((6 != a) != (d > 7))));
	fprint(1, "6 %lld\n", (vlong)((p != q)));
	fprint(1, "7 %lld\n", (vlong)((1 != 0)));
	exits(nil);
}
