/* generated by tools/o9prop.py seed=432156070 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = -56;
	vlong b = -23;
	vlong d = -31;
	int p = 1;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((-155 - -168)));
	fprint(1, "1 %lld\n", (vlong)((14 * a)));
	fprint(1, "2 %lld\n", (vlong)(((~b) + (12 >> 3))));
	fprint(1, "3 %lld\n", (vlong)(((-6 | d) >> 1)));
	fprint(1, "4 %lld\n", (vlong)((!(-5 > a))));
	fprint(1, "5 %lld\n", (vlong)((!q)));
	fprint(1, "6 %lld\n", (vlong)((!0)));
	fprint(1, "7 %lld\n", (vlong)((((0 - (6)) * (9 ^ 7)) != ((a | d) >> 2))));
	exits(nil);
}
