/* generated by tools/o9prop.py seed=231508522 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = -4;
	vlong b = 48;
	vlong d = -2;
	int p = 0;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)(((~d) ^ (d - -9))));
	fprint(1, "1 %lld\n", (vlong)((((3 << 2) / (7 + 7)) % (14 + 7))));
	fprint(1, "2 %lld\n", (vlong)((((11 + -15) >> 3) & ((~b) ^ (13 << 5)))));
	fprint(1, "3 %lld\n", (vlong)(((-190 & d) + (0 - (-8)))));
	fprint(1, "4 %lld\n", (vlong)((((1 && 0) == (!q)) || ((0 - (a)) != (a & -12)))));
	fprint(1, "5 %lld\n", (vlong)((((1 && 0) == (q && 1)) == ((!p) && (5 == 15)))));
	fprint(1, "6 %lld\n", (vlong)((((d >= 6) == (1 && 1)) && ((q != p) && (p || p)))));
	fprint(1, "7 %lld\n", (vlong)((!(4 < a))));
	exits(nil);
}
