/* generated by tools/o9prop.py seed=1604355301 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = -57;
	vlong b = 55;
	vlong d = -47;
	int p = 0;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((-101 ^ 164)));
	fprint(1, "1 %lld\n", (vlong)((((-184 ^ -110) & (13 << 1)) + (0 - ((~4))))));
	fprint(1, "2 %lld\n", (vlong)(((a & -134) ^ (9 >> 2))));
	fprint(1, "3 %lld\n", (vlong)((((81 | 136) | (2 % (6 + 11))) - ((1 / 2) >> 0))));
	fprint(1, "4 %lld\n", (vlong)(((!q) || (q || 0))));
	fprint(1, "5 %lld\n", (vlong)((!(a >= b))));
	fprint(1, "6 %lld\n", (vlong)(((0 / (11 + 11)) <= (~-15))));
	fprint(1, "7 %lld\n", (vlong)(((!(1 && 1)) != ((!0) || (!p)))));
	exits(nil);
}
