/* generated by tools/o9prop.py seed=1402750114 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 49;
	vlong b = 52;
	vlong d = 19;
	int p = 1;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)(((6 / 2) >> 5)));
	fprint(1, "1 %lld\n", (vlong)((9 % 4)));
	fprint(1, "2 %lld\n", (vlong)((d + -105)));
	fprint(1, "3 %lld\n", (vlong)((((7 / 6) & (91 | -59)) + ((a * -8) << 4))));
	fprint(1, "4 %lld\n", (vlong)((!0)));
	fprint(1, "5 %lld\n", (vlong)(((q && 0) == (q || p))));
	fprint(1, "6 %lld\n", (vlong)((6 < d)));
	fprint(1, "7 %lld\n", (vlong)(((!(!0)) && ((p || 0) && (q || 1)))));
	exits(nil);
}
