/* generated by tools/o9prop.py seed=1253978299 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = -29;
	vlong b = -11;
	vlong d = 2;
	int p = 1;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((8 << 0)));
	fprint(1, "1 %lld\n", (vlong)((((8 % (11 + 15)) + (3 | a)) * ((7 << 0) % (1 + 3)))));
	fprint(1, "2 %lld\n", (vlong)((((2 / 12) / 6) << 0)));
	fprint(1, "3 %lld\n", (vlong)(((0 >> 1) >> 3)));
	fprint(1, "4 %lld\n", (vlong)((!(!(!p)))));
	fprint(1, "5 %lld\n", (vlong)((p || 1)));
	fprint(1, "6 %lld\n", (vlong)((1 || q)));
	fprint(1, "7 %lld\n", (vlong)(((!q) != (0 == 1))));
	exits(nil);
}
