/* generated by tools/o9prop.py seed=542111502 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = -25;
	vlong b = 19;
	vlong d = 27;
	int p = 1;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)((((4 << 1) ^ (a | -15)) / (8 + 4))));
	fprint(1, "1 %lld\n", (vlong)(((12 << 4) | (3 << 2))));
	fprint(1, "2 %lld\n", (vlong)((176 - -77)));
	fprint(1, "3 %lld\n", (vlong)((a & a)));
	fprint(1, "4 %lld\n", (vlong)((((0 || 0) && (13 >= -15)) != ((0 >> 5) <= (0 - -4)))));
	fprint(1, "5 %lld\n", (vlong)(((0 - ((a - d))) >= ((12 << 0) * (0 - (-6))))));
	fprint(1, "6 %lld\n", (vlong)((!((7 - -11) < (d * -9)))));
	fprint(1, "7 %lld\n", (vlong)(((p || 0) || (!1))));
	exits(nil);
}
