/* generated by tools/o9prop.py seed=1819629973 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 3;
	vlong b = -55;
	vlong d = 50;
	int p = 1;
	int q = 1;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)(((b | b) + (~4))));
	fprint(1, "1 %lld\n", (vlong)((((15 >> 1) ^ (10 / (3 + 8))) % 7)));
	fprint(1, "2 %lld\n", (vlong)(((8 % 1) * (2 << 0))));
	fprint(1, "3 %lld\n", (vlong)((9 % (7 + 6))));
	fprint(1, "4 %lld\n", (vlong)((1 || p)));
	fprint(1, "5 %lld\n", (vlong)(((q == q) || (a > 0))));
	fprint(1, "6 %lld\n", (vlong)((!((q || p) && (0 == q)))));
	fprint(1, "7 %lld\n", (vlong)((!(!1))));
	exits(nil);
}
