/* generated by tools/o9prop.py seed=2139641256 */
#include <u.h>
#include <libc.h>

void
main(void)
{
	vlong a = 35;
	vlong b = -13;
	vlong d = -16;
	int p = 1;
	int q = 0;
	USED(a); USED(b); USED(d); USED(p); USED(q);
	fprint(1, "vars %lld %lld %lld %lld %lld\n", a, b, d, (vlong)p, (vlong)q);
	fprint(1, "0 %lld\n", (vlong)(((9 / (9 + 1)) & (13 / 6))));
	fprint(1, "1 %lld\n", (vlong)(((-10 ^ -8) >> 0)));
	fprint(1, "2 %lld\n", (vlong)((~((4 << 1) / 3))));
	fprint(1, "3 %lld\n", (vlong)((((5 + -3) >> 3) * ((a | d) >> 2))));
	fprint(1, "4 %lld\n", (vlong)((q == 1)));
	fprint(1, "5 %lld\n", (vlong)(((0 && p) != (!q))));
	fprint(1, "6 %lld\n", (vlong)((((13 % 12) == (13 / 4)) != ((a - d) <= (12 / (8 + 12))))));
	fprint(1, "7 %lld\n", (vlong)((1 && q)));
	exits(nil);
}
